"""init

Revision ID: f1b408d1ee64
Revises: 494f1cec4d97
Create Date: 2025-09-09 13:53:29.898824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b408d1ee64'
down_revision = '494f1cec4d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('set_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'flashcard_set', ['set_id'], ['id'])
        batch_op.drop_column('front')
        batch_op.drop_column('back')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('back', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('front', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('set_id')
        batch_op.drop_column('status')
        batch_op.drop_column('answer')
        batch_op.drop_column('question')

    op.drop_table('flashcard_set')
    # ### end Alembic commands ###
